### Add to the source list
BOARD_SOURCEFILES += leds-arch.c

### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xx

### Add to the source dirs
CONTIKI_TARGET_DIRS += hestag/cc2650

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/hestag/Makefile.tag
